package dev.vibecloud.core.bridge

import dev.vibecloud.api.service.Service
import dev.vibecloud.common.config.BridgeSettings
import dev.vibecloud.common.logging.Logger
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.util.Properties

/**
 * Installs the bridge agent into provisioned backend services:
 *  - copies the agent plugin jar into `plugins/` (kept up to date by size compare),
 *  - writes `plugins/VibeCloud/agent.properties` with cloud URL, service identity, token,
 *    the advertised host, and the ports of running services (for player transfers).
 *
 * Proxies are skipped: they route players but do not host them. The agent jar is resolved from
 * `bridge.agent-jar` when set, otherwise from the distribution layout (`lib/` or `agent/` next to
 * the installation).
 */
class BridgeAgentInstaller(
    private val settings: BridgeSettings,
    private val tokenStore: BridgeTokenStore,
    /** Resolves the URL agents should report to, or null when the bridge is unavailable. */
    private val cloudUrl: () -> String?,
    private val agentJarResolver: () -> Path?,
    private val logger: Logger,
    /** Resolves the host clients should be transferred to, or null when transfers are not advertised. */
    private val advertisedHost: () -> String? = { null },
    /** Current name→port map of running services, written to the agent config for transfers. */
    private val servicePorts: () -> Map<String, Int> = { emptyMap() },
) {
    fun install(service: Service) {
        if (!settings.enabled || service.type.isProxy) return
        try {
            installInternal(service)
        } catch (failure: Exception) {
            // The agent is an enhancement; a failed installation must never block a start.
            logger.warn("Could not install the VibeCloud agent into ${service.name}: ${failure.message}")
        }
    }

    private fun installInternal(service: Service) {
        val url = cloudUrl() ?: run {
            logger.debug("Bridge endpoint is unavailable; skipping agent installation for ${service.name}")
            return
        }
        val agentJar = agentJarResolver()
        if (agentJar == null || !Files.isRegularFile(agentJar)) {
            // Warn (once per process) so a missing agent jar is diagnosable — it is the reason
            // player counts would stay at zero.
            if (missingJarWarned.compareAndSet(false, true)) {
                logger.warn(
                    "No bridge agent jar found (looked for lib/$AGENT_JAR_NAME next to the installation); " +
                            "services will not report player counts",
                )
            }
            return
        }
        val pluginsDirectory = service.directory.resolve("plugins")
        Files.createDirectories(pluginsDirectory)
        val targetJar = pluginsDirectory.resolve(AGENT_JAR_NAME)
        // Keep the agent up to date: replace it whenever the bundled jar differs (size is a
        // reliable discriminator here because we build and ship this jar ourselves).
        val outdated = !Files.isRegularFile(targetJar) || Files.size(targetJar) != Files.size(agentJar)
        if (outdated) {
            Files.copy(agentJar, targetJar, StandardCopyOption.REPLACE_EXISTING)
            logger.info("Installed VibeCloud agent plugin into ${service.name}")
        }
        val configDirectory = pluginsDirectory.resolve("VibeCloud")
        Files.createDirectories(configDirectory)
        val properties = Properties().apply {
            setProperty("cloud-url", url)
            setProperty("service-id", service.id)
            setProperty("service-name", service.name)
            setProperty("group-name", service.groupName)
            setProperty("token", tokenStore.obtain())
            setProperty("heartbeat-interval-seconds", settings.heartbeatInterval.seconds.toString())
            advertisedHost().takeIf { !it.isNullOrBlank() }?.let { setProperty("advertised-host", it) }
            // Ports of every running service so the agent can resolve transfer targets.
            servicePorts().forEach { (name, port) -> setProperty("target.$name.port", port.toString()) }
        }
        Files.newOutputStream(configDirectory.resolve("agent.properties")).use { output ->
            properties.store(output, "Generated by VibeCloud. Do not commit; contains a secret token.")
        }
    }

    companion object {
        const val AGENT_JAR_NAME = "VibeCloud-Agent.jar"

        private val missingJarWarned = java.util.concurrent.atomic.AtomicBoolean(false)

        /**
         * Default lookup order for the bundled agent jar: an explicit `agent/` folder next to the
         * installation, then the Gradle distribution `lib/` folder.
         */
        fun defaultAgentJarResolver(configFileParent: Path?): () -> Path? = {
            val searchRoots = buildList {
                configFileParent?.let { add(it) }
                Path.of(".").toAbsolutePath().normalize().let { add(it) }
            }
            searchRoots.asSequence()
                .map { root -> root.resolve("agent").resolve(AGENT_JAR_NAME) }
                .firstOrNull(Files::isRegularFile)
                ?: searchRoots.asSequence()
                    .map { root -> root.resolve("lib").resolve(AGENT_JAR_NAME) }
                    .firstOrNull(Files::isRegularFile)
        }
    }
}
